### ISSUE TITLE
WP-CLI status exit (1)

### ISSUE THREAD

**Issue by subrato** [chriszarate/docker-wordpress-vip-go#1]
I have download this repo and run docker-compose up -d and every single time I have tried, I get Exit 1 state for wp-cli. The only way I can use wp cli is going into the wordpress container and manually install wp-cli. Is there something that I missing here?

**Comment by chriszarate** [comment]
The `wp-cli` container is designed to run only when you executing a wp-cli command (much like wp-cli itself). So a `Exit 1` state is normal and intended. The container starts whenever you run a command in the wp-cli container.
